class Consts:
    KAFKA_CONSUMER_CLIENT_ID = "port-agent"
    DEFAULT_HTTP_METHOD = "POST"
    MISSING_VALUE = "MISSING"
    VALID_STREAMER_TYPES = ["KAFKA", "POLLING"]
    PORT_EXEC_AGENT_CLAIMING_KEY = "_PORT_EXEC_AGENT"
    ACTION_RUN_ID_PREFIX = "r_"
    WF_NODE_RUN_ID_PREFIX = "wfnr_"


consts = Consts()
